export enum GameEvent {
    StartGame = 'startGame',
    StartTestGame = 'startTestGame',
    PlayerAnswer = 'playerAnswer',
    OrganisatorLeft = 'organisatorLeft',
    NextQuestion = 'nextQuestion',
    ShowResult = 'showResult',
    PlayerAnswerQRL = 'playerAnswerQRL',
    PlayerAnswerTest = 'playerAnswerTest',
    PlayerAnswerNoSubmit = 'playerAnswerNoSubmit',
    JoinTestRoom = 'joinTestRoom',
    LeaveTestRoom = 'leaveTestRoom',
    SubmitTestRoom = 'submitTestRoom',
    SelectChoice = 'selectChoice',
    PlayerAbandon = 'playerAbandon',

    ChangeTopBar = 'changeTopBar',
    GiveScore = 'giveScore',
    GivePlayerScore = 'givePlayerScore',
    GiveQuestion = 'giveQuestion',
    GiveStatAnswer = 'giveStatAnswer',
    TimerDoneClient = 'timerDoneClient',
    EndGame = 'endGame',
    CanChangeQuestion = 'canChangeQuestion',
    EveryPlayerAnswered = 'everyPlayerAnswered',
    GiveTotalQuestion = 'giveTotalQuestion',
    GameResult = 'gameResult',
    GameDone = 'gameDone',
    GiveCurrentStatAnswer = 'giveCurrentStatAnswer',
    GiveCurrentQuestionAnswers = 'giveCurrentQuestionAnswers',
    GiveCurrentQuestion = 'giveCurrentQuestion',
    GiveScores = 'giveScores',
    RoutePlayerResult = 'routePlayerResult',
    PlayerLeft = 'playerLeft',
    OrgLeft = 'orgLeft',
    SendQRLAnswersToOrg = 'SendQRLAnswersToOrg',
    giveGraph = 'giveGraph',
    sendGraphs = 'sendGraphs',
    receiveQRLScore = 'receiveQRLScore',
    QRLScore = 'QRLScore',
    askQRLAnswers = 'askQRLAnswers',
    askQRLAnswersResponse = 'askQRLAnswersResponse',

    firstInteractionQRL = 'firstInteractionQRL',

    ResetStates = 'ResetStates',
    SubmitForColor = 'SubmitForColor',
    UpdateColor = 'UpdateColor',
    playerActive = 'playerActive',
    ActivePlayer = 'ActivePlayer',

    pauseTimer = 'pauseTimer',
    resumeTimer = 'resumeTimer',
    panicMode = 'panicMode',
    canEnablePanic = 'canEnablePanic',
    canActivatePanicMode = 'canActivatePanicMode',
    playPanic = 'playPanic',
    panicSound = 'panicSound',

    SortPlayer = 'SortPlayer',
    PlayerListSorted = 'PlayerListSorted',
    TypeOfSort = 'TypeOfSort',
    Sorting = 'Sorting',

    playerIdle = 'playerIdle',
    IdlePlayer = 'IdlePlayer',

    routePlayerResult = 'routePlayerResult',
}
