export enum RoomEvent {
    CreateRoom = 'CreateRoom',
    DeleteRoom = 'DeleteRoom',
    JoinGame = 'JoinGame',
    LeaveRoom = 'LeaveRoom',
    RemovePlayer = 'RemovePlayer',
    LockRoom = 'LockRoom',
    Start = 'Start',
    RemovePlayerRoom = 'removePlayerRoom',
    RoomCreated = 'RoomCreated',
    GetRoomID = 'GetRoomID',
    Kicked = 'Kicked',
    RoomLeaved = 'RoomLeaved',
    UpdateRoomPlayer = 'UpdateRoomPlayer',
    ErrorMessage = 'ErrorMessage',
    JoinRoom = 'JoinRoom',
    RoomStateChanged = 'RoomStateChanged',
    SocketList = 'SocketList',
    DisplayTimer = 'displayTimer',
    RoutePlayer = 'routePlayer',
}
