export enum SocketEvents {
    Validate = 'validate',
    ValidateACK = 'validateWithAck',
    BroadcastAll = 'broadcastAll',
    JoinRoom = 'joinRoom',
    LeaveRoom = 'LeaveRoom',
    JoinRoomFailed = 'joinRoomFailed',
    RoomMessage = 'roomMessage',
    RoomCode = 'RoomCode',

    WordValidated = 'wordValidated',
    MassMessage = 'massMessage',
    Hello = 'hello',
    Clock = 'clock',
    CreateRoom = "CreateRoom",
    DeleteRoom = "DeleteRoom",
    RoomCreated = "RoomCreated",
    RoomDeleted = 'RoomDeleted',
    JoinGame = "JoinGame",
    RoomLeaved = 'RoomLeaved',
    GameJoined = "GameJoined",
    JoinGameFailed = "GameJoinFailed",
    CreatePlayer = "CreatePlayer",
}